USE [master]
GO

/****** Object:  Database [SCADASYSTEM]    Script Date: 17/05/2026 13:32:15 ******/
CREATE DATABASE [SCADASYSTEM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SCADASYSTEM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\SCADASYSTEM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SCADASYSTEM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\SCADASYSTEM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SCADASYSTEM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SCADASYSTEM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET ARITHABORT OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SCADASYSTEM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SCADASYSTEM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SCADASYSTEM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SCADASYSTEM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SCADASYSTEM] SET  MULTI_USER 
GO

ALTER DATABASE [SCADASYSTEM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SCADASYSTEM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SCADASYSTEM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SCADASYSTEM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SCADASYSTEM] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [SCADASYSTEM] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SCADASYSTEM] SET QUERY_STORE = ON
GO

ALTER DATABASE [SCADASYSTEM] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SCADASYSTEM] SET  READ_WRITE 
GO

